Repository react-native-share/react-native-share, pull requests merged in 2019-05, with the labels that each got.

#489 chore: update iOS target to 9.0 to match react-native min version
  ios/RNShare.xcodeproj/project.pbxproj
Labels: os: ios

#495 Feature/improving-project-mds
  README.md
  example/README.MD
  example/package.json
Labels: docs

#498 Chore/adding install master instruction
  README.md
Labels: docs

#499 fix android sms share default app issue
  android/src/main/java/cl/json/social/SMSShare.java
Labels: enhancement, os: android

#502 Docs/fixing example steps
  example/README.MD
Labels: docs

#503 Adding stale config to handle stale issues following react-native as …
  .github/stale.yml
Labels: enhancement
