Repository react-native-share/react-native-share, pull requests merged in 2020-01, with the labels that each got.

#675 build: setting project version to 3.0.0
  package.json
Labels: dependencies

#680 ci: Remove duplicate line
  .github/stale.yml
Labels: ci

#683 ci: adding new job config
  .circleci/config.yml
  CHANGELOG.md
Labels: ci, enhancement

#691 ci: applying config to set MAX_WORKERS to 2
  .circleci/config.yml
  example/metro.config.js
Labels: ci

#692 fix ci envs at job
  .circleci/config.yml
Labels: ci
